// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEyralbj6fiUYpBV7JJJ90zV_G3KwmYrA',
    appId: '1:293400889675:web:c18188be8ad077cfe900ce',
    messagingSenderId: '293400889675',
    projectId: 'letss-11cc7',
    authDomain: 'letss-11cc7.firebaseapp.com',
    storageBucket: 'letss-11cc7.appspot.com',
    measurementId: 'G-EMZMBZE43Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW2NGi3lLK7u85bx6LTRau_VhNZRpTuGA',
    appId: '1:293400889675:android:5b2317b841f8775de900ce',
    messagingSenderId: '293400889675',
    projectId: 'letss-11cc7',
    storageBucket: 'letss-11cc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKVmv4MGOdV-Ha79aKCJVvnyYynTHSeZ0',
    appId: '1:293400889675:ios:a609a153c43f534ee900ce',
    messagingSenderId: '293400889675',
    projectId: 'letss-11cc7',
    storageBucket: 'letss-11cc7.appspot.com',
    androidClientId: '293400889675-57nqmrlp1ov83u3sjbacb55khjrm849k.apps.googleusercontent.com',
    iosClientId: '293400889675-j9cj00vtvqmjpn9etd9d67pm1md3rp7j.apps.googleusercontent.com',
    iosBundleId: 'com.letss.letssapp',
  );

}